dataset: POKEMON
n_noise_features: 100
epochs: 1000
disc_steps: 5
gen_steps: 1
discriminator_filters: 128
generator_filters: 128
batch_size: 64
print_every: 5
checkpoints: 50
rolling_window: 100
discriminator_label_noise: False
discriminator_input_noise: False
resume_training: None